[tool.poetry]
name = "py-hpsu-monitor"
version = "0.1.0"
description = ""
authors = ["Felix Stürmer <stuermer@weltenwort.de>"]

[tool.poetry.dependencies]
python = "^3.8"
python-can = "^3.3.3"
typer = "^0.3.2"
tomlkit = "^0.7.0"
typing_extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.6.0"
black = "^20.8b1"
pytest-watch = "^4.2.0"
fabric = {version = "^2.5.0", optional = true}

[tool.poetry.extras]
deploy = ["fabric"]

[tool.poetry.scripts]
py-hpsu-monitor = "py_hpsu_monitor.cli:app"

[tool.black]
disable = ["C0330", "C0326"]
max-line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
