name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: Run tests on ${{ matrix.os }} using Python ${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.8]
        poetry_version: [1.0.10]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry_version }}
      - name: View poetry --help
        run: poetry run pytest
